android.enableJetifier=true
android.useAndroidX=true
android.nonTransitiveRClass=true

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
org.gradle.daemon.idletimeout=1800000
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.parallel=true

android.defaults.buildfeatures.buildconfig=true

android.enableR8.fullMode=false
